Fix tox test due to changed stdout
ERROR: InvocationError: "C:\\hexdump\\.tox\\py34\\Scripts\\python -c import filecmp,sys; sys.exit(not filecmp.cmp('hextest.txt', 'toxtest.txt'))"
___________________________________ summary ___________________________________
ERROR:   py27: commands failed
ERROR:   py34: commands failed